name: pmd

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  check-and-run:
    if: github.repository_owner == 'PreMiD'
    name: Update assets
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install pmd
        run: npm ci

      - name: Update assets
        env:
          CDN_TOKEN: ${{ secrets.CDN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          # Configure git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Run PMD update-assets command
          npx pmd update-assets
